interface IIndexConstants
{
    GET_COMPANIES_REQUEST: string,
    GET_COMPANIES_SUCCESS: string,
    GET_COMPANIES_ERROR: string,
}

export const indexConstants: IIndexConstants =
{
    GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
    GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_ERROR: 'GET_COMPANIES_ERROR',
}